#!/usr/bin/env python3
"""Translate zh-Hans entries in Localizable.xcstrings from English to Chinese."""

import json
import re
import sys

TRANSLATIONS = {
    # === Plural / variation strings ===
    "(%lld Issue)": "（%lld 个问题）",
    "(%lld Issues)": "（%lld 个问题）",
    "%d day": "%d 天",
    "%d days": "%d 天",
    "%d hour": "%d 小时",
    "%d hours": "%d 小时",
    "%d minute": "%d 分钟",
    "%d minutes": "%d 分钟",
    "%d month": "%d 个月",
    "%d months": "%d 个月",
    "%lld Episode": "%lld 集",
    "%lld Episodes": "%lld 集",
    "%lld Movie": "%lld 部电影",
    "%lld Movies": "%lld 部电影",
    "%lld Season": "%lld 季",
    "%lld Seasons": "%lld 季",
    "%lld Series": "%lld 部剧集",
    "%lld Tag": "%lld 个标签",
    "%lld Tags": "%lld 个标签",
    "%lld Task": "%lld 个任务",
    "%lld Tasks": "%lld 个任务",
    "+%lld more...": "+%lld 更多...",
    "Season %lld": "第 %lld 季",

    # === Format strings with %@ ===
    "%@ at %@": "%1$@ %2$@",
    "%@ does not start an automatic search when adding media, but you can.": "%@ 在添加媒体时不会自动搜索，但你可以手动搜索。",
    "%@ years": "%@ 年",
    "%@.": "%@。",
    "%1$@ downloaded successfully and imported from %2$@.": "%1$@ 下载成功，已从 %2$@ 导入。",
    "%1$@ grabbed from %2$@ and sent to %3$@.": "%1$@ 已从 %2$@ 抓取并发送至 %3$@。",
    "Alternatively, %@ comes with many notification integrations that can be self-hosted.": "或者，%@ 自带许多可自行托管的消息通知集成。",
    "An unknown error occurred: %@": "发生未知错误：%@",
    "Bad status code: %lld": "错误状态码：%lld",
    "Basic Authentication is for advanced server management tools and will not work with regular %@ login credentials.": "Basic Authentication 适用于高级服务器管理工具，无法使用常规的 %@ 登录凭据。",
    "Blocks this release from being redownloaded via Automatic Search or RSS.": "阻止该发布通过自动搜索或 RSS 重新下载。",
    "Check the spelling or try [adding the movie](%@).": "请检查拼写或尝试[添加电影](%@)。",
    "Check the spelling or try [adding the series](%@).": "请检查拼写或尝试[添加剧集](%@)。",
    "Connect a %@ instance under %@.": "在 %2$@ 下连接 %1$@ 实例。",
    "e.g. %@": "例如 %@",
    "File was deleted either manually or by a client through the API.": "文件已被手动删除，或被客户端通过 API 删除。",
    "File was deleted to import an upgrade.": "文件已被删除以导入升级版本。",
    "File was not found on disk so it was unlinked from the episode in the database.": "磁盘上未找到文件，已从数据库中该剧集取消关联。",
    "File was not found on disk so it was unlinked from the movie in the database.": "磁盘上未找到文件，已从数据库中该电影取消关联。",
    "Instance URL is not valid: %@": "实例 URL 无效：%@",
    "Local network access must be granted in %@ to connect to instances using private IP addresses.": "必须在 %@ 中授予本地网络访问权限，才能通过私有 IP 地址连接实例。",
    "Looking to [add a new movie](%@)?": "想要[添加新电影](%@)？",
    "Looking to [add a new series](%@)?": "想要[添加新剧集](%@)？",
    "Move the movie files to \"%@\"?": "将电影文件移动到「%@」？",
    "Move the series files to \"%@\"?": "将剧集文件移动到「%@」？",
    "No %@ Instance": "没有 %@ 实例",
    "No releases found for \"%@\".": "未找到「%@」的发布。",
    "No releases match \"%@\".": "没有匹配「%@」的发布。",
    "No releases match the selected filters and \"%@\".": "没有匹配所选过滤器和「%@」的发布。",
    "No Results for \"%@\"": "未找到「%@」的结果",
    "Notification settings for each instance are shared between devices. To disable notifications for a specific device go to %@.": "每个实例的通知设置会在设备间共享。如需在特定设备上禁用通知，请前往 %@。",
    "Notifications are disabled, please enable them in %@.": "通知已禁用，请在 %@ 中启用。",
    "Notifications require a subscription to %@.": "通知功能需要订阅 %@。",
    "Notifications require an Apple Account. Please sign in, or enable iCloud Drive in the iCloud settings (%1$@).": "通知功能需要 Apple 账户。请登录，或在 iCloud 设置中启用 iCloud 云盘（%1$@）。",
    "Open %@": "打开 %@",
    "Open in %@": "在 %@ 中打开",
    "Optimizes API calls for instances that load unusually slowly and encounter timeouts frequently.": "针对加载异常缓慢且频繁超时的实例优化 API 调用。",
    "Preferred language and other app-related settings can be configured in the [System Settings](#link).": "首选语言和其他应用相关设置可在[系统设置](#link)中配置。",
    "Prevent from being readded to library by lists.": "防止通过列表重新添加到库中。",
    "Server returned %lld status code.": "服务器返回了 %lld 状态码。",
    "Subscription unlocks instance notifications, alternate app icons and supports the continued indie development of %@.": "订阅可解锁实例通知、备用应用图标，并支持 %@ 的持续独立开发。",
    "The release for this movie could not be determined and it may not import automatically. Do you want to grab \"%@\"?": "无法确定该电影的发布版本，可能无法自动导入。是否要抓取「%@」？",
    "The release for this series/episode could not be determined and it may not import automatically. Do you want to grab \"%@\"?": "无法确定该剧集/集数的发布版本，可能无法自动导入。是否要抓取「%@」？",
    "The URL used to access the %@ web interface.": "用于访问 %@ Web 界面的 URL。",
    "Unsupported URL: %@": "不支持的 URL：%@",
    "URL identified itself as a %@ instance, not a %@ instance.": "该 URL 识别为 %1$@ 实例，而非 %2$@ 实例。",
    "Version %@ (%@)": "版本 %@（%@）",
    "What's New in %@": "%@ 的新功能",
    "Whether to ignore the download, or remove it and its file(s) from the download client.": "选择忽略该下载，或将其及文件从下载客户端中删除。",

    # === UI Labels & Buttons ===
    "About": "关于",
    "Accent Color": "强调色",
    "Active": "已激活",
    "Activity": "活动",
    "Add Authentication": "添加认证",
    "Add Exclusion": "添加排除",
    "Add Header": "添加 Header",
    "Add Instance": "添加实例",
    "Add Movie": "添加电影",
    "Add Series": "添加剧集",
    "Added": "已添加",
    "Age": "年龄",
    "Airing": "播出中",
    "Alias": "别名",
    "All Episodes": "所有集数",
    "All Events": "所有事件",
    "All instance queues are empty.": "所有实例队列为空。",
    "All Movies": "所有电影",
    "All TV Series": "所有电视剧",
    "An error occurred.": "发生错误。",
    "An unexpected error occurred.": "发生意外错误。",
    "Anime": "动漫",
    "Announced": "已公布",
    "Any": "全部",
    "Any Client": "任意客户端",
    "Any Folder": "任意文件夹",
    "Any Format": "任意格式",
    "Any Indexer": "任意索引器",
    "Any Instance": "任意实例",
    "Any Language": "任意语言",
    "Any Protocol": "任意协议",
    "Any Quality": "任意质量",
    "API Key": "API 密钥",
    "App Icon": "应用图标",
    "Appearance": "外观",
    "Application Updated": "应用已更新",
    "Approved": "已批准",
    "Are you attempting to connect to a private IP address from outside its network?": "是否尝试从网络外部连接到私有 IP 地址？",
    "Are you sure you want to delete the instance?": "确定要删除该实例吗？",
    "Are you sure you want to erase all settings?": "确定要清除所有设置吗？",
    "Are you sure?": "确定吗？",
    "Ascending": "升序",
    "At least you're not on hold.": "至少你没有在等待。",
    "Audio": "音频",
    "Authentication": "认证",
    "Automatic": "自动",
    "Automatic Search": "自动搜索",
    "Availability": "可用性",
    "Barbie": "Barbie",
    "Basic Authentication": "Basic Authentication",
    "Bitrate": "比特率",
    "Blocklist Release": "加入黑名单",
    "Books": "图书",
    "Bug Report Sent": "Bug 报告已发送",
    "Calendar": "日历",
    "Cancel": "取消",
    "Cards": "卡片",
    "Channels": "声道",
    "Clear Filters": "清除筛选",
    "Clear Image Cache": "清除图片缓存",
    "Client": "客户端",
    "Close": "关闭",
    "Codec": "编码",
    "Color Depth": "色彩深度",
    "Connected": "已连接",
    "Connecting...": "连接中...",
    "Connection Failed": "连接失败",
    "Connection Failure": "连接失败",
    "Continue": "继续",
    "Continuing": "续播",
    "Contribute": "贡献",
    "Contribute on GitHub": "在 GitHub 上贡献",
    "Copy Link": "复制链接",
    "Custom Format": "自定义格式",
    "Custom Formats": "自定义格式",
    "Custom Headers can be used to access instances protected by Zero Trust services.": "自定义 Header 可用于访问受 Zero Trust 服务保护的实例。",
    "Custom Score": "自定义评分",
    "Daily": "每日",
    "Dangling": "悬空",
    "Dark": "深色",
    "Default": "默认",
    "Delete": "删除",
    "Delete File": "删除文件",
    "Delete Files": "删除文件",
    "Delete Instance": "删除实例",
    "Delete Movie": "删除电影",
    "Delete Series": "删除剧集",
    "Delete Spotlight Index": "删除 Spotlight 索引",
    "Deleted": "已删除",
    "Deleting Files": "正在删除文件",
    "Descending": "降序",
    "Details": "详情",
    "Digital Release": "数字发布",
    "Direction": "方向",
    "Discovering new ways of making you wait.": "正在寻找让你等待的新方式。",
    "Disk Space": "磁盘空间",
    "Display": "显示",
    "Download": "下载",
    "download client": "下载客户端",
    "Download Client Unavailable": "下载客户端不可用",
    "Download Client Warning": "下载客户端警告",
    "Download Failed": "下载失败",
    "Download Ignored": "下载已忽略",
    "Download Queued": "下载已排队",
    "Download Release": "下载发布",
    "Downloaded": "已下载",
    "Downloading": "下载中",
    "Dynamic Range": "动态范围",
    "Edit": "编辑",
    "Email": "邮件",
    "Enable Notifications": "启用通知",
    "Ended": "已完结",
    "Enter a valid URL.": "请输入有效的 URL。",
    "Enter an instance label.": "请输入实例标签。",
    "Episode": "集",
    "Episode Deleted": "剧集已删除",
    "Episode file was renamed.": "剧集文件已重命名。",
    "Episode Renamed": "剧集已重命名",
    "Episode Search Queued": "剧集搜索已排队",
    "Episodes": "集数",
    "Error": "错误",
    "Event Type": "事件类型",
    "Everything": "全部",
    "Existing Episodes": "现有剧集",
    "Expired": "已过期",
    "Failed": "失败",
    "File": "文件",
    "File Deleted": "文件已删除",
    "File Imported": "文件已导入",
    "File Size": "文件大小",
    "File Upgraded": "文件已升级",
    "Files": "文件",
    "Files & History": "文件与历史",
    "Filter": "筛选",
    "First Season": "第一季",
    "Fitness": "健身",
    "Flags": "标志",
    "Folder Imported": "文件夹已导入",
    "Framerate": "帧率",
    "FreeLeech": "免费下载",
    "Future Episodes": "未来剧集",
    "Genre": "类型",
    "Grab Release": "抓取发布",
    "Grabbed": "已抓取",
    "Grid": "网格",
    "Header name": "Header 名称",
    "Header value": "Header 值",
    "Headers": "Headers",
    "Health Issue": "健康问题",
    "Health Restored": "健康已恢复",
    "Hide Specials": "隐藏特辑",
    "History": "历史",
    "Hold on, this may take a moment.": "请稍候，这可能需要一点时间。",
    "Home": "首页",
    "Icons": "图标",
    "Identifier": "标识符",
    "Ignored": "已忽略",
    "Import": "导入",
    "Import Blocked": "导入被阻止",
    "Import Completed": "导入完成",
    "Import Pending": "待导入",
    "Import Queued": "导入已排队",
    "Imported": "已导入",
    "Importing": "导入中",
    "In Cinemas": "影院上映",
    "In Queue": "队列中",
    "Inactive": "未激活",
    "Include Warnings": "包含警告",
    "indexer": "索引器",
    "Indexer": "索引器",
    "Information": "信息",
    "Instance": "实例",
    "Instances": "实例",
    "Integrations": "集成",
    "Interactive": "交互式",
    "Interactive Search": "交互式搜索",
    "Invalid Instance Label": "无效的实例标签",
    "Invalid URL": "无效的 URL",
    "Is this running on Windows?": "是否在 Windows 上运行？",
    "Issues": "问题",
    "Join the Discord": "加入 Discord",
    "Just now": "刚刚",
    "Just testing your patience.": "只是在考验你的耐心。",
    "Label": "标签",
    "Language": "语言",
    "Languages": "语言",
    "Last Season": "最后一季",
    "Latest": "最新",
    "Leave a Review": "留下评价",
    "Let's hope it's worth the wait.": "希望等待是值得的。",
    "Light": "浅色",
    "Link": "链接",
    "Link Copied": "链接已复制",
    "Load More": "加载更多",
    "Loading...": "加载中...",
    "Local Network Access Denied": "本地网络访问被拒绝",
    "Local network access must be granted in System Settings to connect to instances on private IP addresses.": "必须在「系统设置」中授予本地网络访问权限，才能连接使用私有 IP 地址的实例。",
    "Long-press any file to delete it.": "长按文件即可删除。",
    "Mail": "邮件",
    "Manual Import": "手动导入",
    "Manual Interaction Required": "需要手动操作",
    "Match Type": "匹配类型",
    "Media Type": "媒体类型",
    "Metadata": "元数据",
    "Midseason Finale": "季中结局",
    "Min. Availability": "最低可用性",
    "Minimum Availability": "最低可用性",
    "Missing": "缺失",
    "Missing Episodes": "缺失的剧集",
    "Monitor": "监控",
    "Monitor New Seasons": "监控新季",
    "Monitor Specials": "监控特辑",
    "Monitored": "已监控",
    "Monitored Search Queued": "已监控搜索已排队",
    "Monochrome": "单色",
    "Move Files": "移动文件",
    "Movie": "电影",
    "Movie + Collection": "电影 + 合集",
    "Movie Added": "电影已添加",
    "Movie Deleted": "电影已删除",
    "Movie Downloading": "电影下载中",
    "Movie File Deleted": "电影文件已删除",
    "Movie file was renamed.": "电影文件已重命名。",
    "Movie has no files.": "该电影没有文件。",
    "Movie has no history.": "该电影没有历史记录。",
    "Movie Imported": "电影已导入",
    "Movie imported from folder.": "电影已从文件夹导入。",
    "Movie Renamed": "电影已重命名",
    "Movie Search Queued": "电影搜索已排队",
    "Movie Upgraded": "电影已升级",
    "Movies": "电影",
    "Multi-Episode": "多集",
    "Multilingual": "多语言",
    "Music": "音乐",
    "Network": "网络",
    "New Seasons": "新季",
    "Next Airing": "下次播出",
    "No": "否",
    "No Automatic Search": "无自动搜索",
    "No Events": "无事件",
    "No Events Match": "无匹配事件",
    "No events match the selected filters.": "没有匹配所选筛选条件的事件。",
    "No importable files found.": "未找到可导入的文件。",
    "No Instance": "无实例",
    "No Internet Connection": "无网络连接",
    "No Movies Match": "无匹配电影",
    "No movies match the selected filters.": "没有匹配所选筛选条件的电影。",
    "No Releases Found": "未找到发布",
    "No Releases Match": "无匹配发布",
    "No releases match the selected filters.": "没有匹配所选筛选条件的发布。",
    "No Series Match": "无匹配剧集",
    "No series match the selected filters.": "没有匹配所选筛选条件的剧集。",
    "None": "无",
    "Not Subscribed": "未订阅",
    "Notes": "备注",
    "Notifications": "通知",
    "OK": "确定",
    "Open": "打开",
    "Open ${target}": "打开 ${target}",
    "Open In...": "打开方式...",
    "Open Ruddarr": "打开 Ruddarr",
    "Open Website": "打开网站",
    "Original": "原始",
    "Other": "其他",
    "Password": "密码",
    "Paste": "粘贴",
    "Paused": "已暂停",
    "Peers": "用户数",
    "Pending": "待处理",
    "Permanently erase the folder and its contents.": "永久删除该文件夹及其内容。",
    "Physical Release": "实体发布",
    "Pilot Episode": "试播集",
    "Please check your internet connection and try again.": "请检查网络连接后重试。",
    "Podcasts": "播客",
    "Popular This Week": "本周热门",
    "Posters": "海报",
    "Preferences": "偏好设置",
    "Premieres": "首播",
    "Preserve": "保留",
    "Previous Airing": "上次播出",
    "Proper": "Proper",
    "Protocol": "协议",
    "Provide a detailed description of the issue along with the exact steps to reproduce it.": "请详细描述问题，并提供复现步骤。",
    "Published": "已发布",
    "Quality": "质量",
    "Quality Profile": "质量配置",
    "Queued": "已排队",
    "Queues Empty": "队列为空",
    "Rating": "评分",
    "Recent Episodes": "最近剧集",
    "Refresh": "刷新",
    "Refresh Queued": "刷新已排队",
    "Release Downloading": "发布下载中",
    "Release Filters": "发布筛选",
    "Release Grabbed": "发布已抓取",
    "Release Group": "发布组",
    "Release Notes": "更新日志",
    "Release Push": "发布推送",
    "Release Rejected": "发布已拒绝",
    "Release Type": "发布类型",
    "Released": "已发布",
    "Relevant": "相关",
    "Remove": "移除",
    "Remove from Client": "从客户端移除",
    "Remove Task": "移除任务",
    "Renamed": "已重命名",
    "Repack": "重新打包",
    "Report an Issue": "报告问题",
    "Reset": "重置",
    "Reset All Settings": "重置所有设置",
    "Resolution": "分辨率",
    "Response Decoding Error": "响应解码错误",
    "Retry": "重试",
    "Revoked": "已撤销",
    "Root Folder": "根文件夹",
    "Runtime": "时长",
    "Save": "保存",
    "Scan Type": "扫描类型",
    "Score": "评分",
    "Search": "搜索",
    "Search for Movie": "搜索电影",
    "Search for movie with ${name}": "搜索电影：${name}",
    "Search for Replacement": "搜索替代",
    "Search for TV Series": "搜索电视剧",
    "Search for TV series with ${name}": "搜索电视剧：${name}",
    "Search Monitored": "搜索已监控",
    "Searching...": "搜索中...",
    "Season Files Deleted": "季文件已删除",
    "Season Finale": "季终",
    "Season Folders": "季文件夹",
    "Season Pack": "季合集",
    "Season Premiere": "季首播",
    "Season Search Queued": "季搜索已排队",
    "Seasons": "季",
    "Seeders": "做种数",
    "Sending push notifications to devices requires reliable server infrastructure, which incurs monthly operating expenses for this free, open-source project.": "向设备发送推送通知需要可靠的服务器基础设施，这给这个免费的开源项目带来了每月的运营成本。",
    "Series": "剧集",
    "Series Added": "剧集已添加",
    "Series Deleted": "剧集已删除",
    "Series Finale": "全剧终",
    "Series imported from folder.": "剧集已从文件夹导入。",
    "Series Not Monitored": "剧集未监控",
    "Series Premiere": "首播集",
    "Series Type": "剧集类型",
    "Server Error Response": "服务器错误响应",
    "Settings": "设置",
    "Share App": "分享 App",
    "Show Advanced Settings": "显示高级设置",
    "Single Episode": "单集",
    "Slow Instance": "慢速实例",
    "Some releases are hidden by the selected filters.": "部分发布被所选筛选条件隐藏。",
    "Something Went Wrong": "出了点问题",
    "Sort By": "排序方式",
    "Source": "来源",
    "Special": "特辑",
    "Specials": "特辑",
    "Standard": "标准",
    "Status": "状态",
    "Still searching for releases.": "仍在搜索发布。",
    "Streams": "流",
    "Studio": "工作室",
    "Submit": "提交",
    "Subscription": "订阅",
    "Subtitles": "字幕",
    "System": "系统",
    "System Settings": "系统设置",
    "System Settings > Notifications > %@": "系统设置 > 通知 > %@",
    "System Settings > Privacy & Security > Local Network": "系统设置 > 隐私与安全性 > 本地网络",
    "Tab": "标签页",
    "Tags": "标签",
    "TBA": "待定",
    "TestFlight for macOS": "macOS 版 TestFlight",
    "The API Key can be found in the web interface under \"Settings > General > Security\".": "API 密钥可在 Web 界面的「设置 > 通用 > 安全」中找到。",
    "The credentials will be encoded and added as an \"Authorization\" header.": "凭据将被编码并添加为「Authorization」Header。",
    "This will permanently erase all episode files of this season.": "这将永久删除本季的所有剧集文件。",
    "This will permanently erase the episode file.": "这将永久删除该剧集文件。",
    "This will permanently erase the movie file.": "这将永久删除该电影文件。",
    "Time flies when you're having fun.": "快乐时光总是短暂的。",
    "Title": "标题",
    "To monitor a season or episode, the series itself must be monitored.": "要监控某季或某集，必须先监控该剧集。",
    "Today": "今天",
    "Tomorrow": "明天",
    "Torrent": "Torrent",
    "Trailer": "预告片",
    "Translate the App": "翻译应用",
    "Try again later.": "请稍后再试。",
    "Try holding your breath.": "试试憋气。",
    "Type": "类型",
    "Unable to Import Automatically": "无法自动导入",
    "Unaired": "未播出",
    "Unannounced": "未公布",
    "Uncoded": "未编码",
    "Undetermined": "未确定",
    "Unknown": "未知",
    "Unknown Event": "未知事件",
    "Unknown event.": "未知事件。",
    "Unmonitor Specials": "取消监控特辑",
    "Unmonitored": "未监控",
    "Unrated": "未评级",
    "Unreleased": "未发布",
    "Unwanted": "不需要",
    "Upcoming": "即将到来",
    "Upgrade to Sonarr v4.0.5 or newer.": "请升级到 Sonarr v4.0.5 或更高版本。",
    "URL": "URL",
    "URL must start with \"http://\" or \"https://\".": "URL 必须以「http://」或「https://」开头。",
    "URL Not Reachable": "URL 不可达",
    "URLs must be non-local, \"localhost\" and \"127.0.0.1\" will not work.": "URL 不能为本地地址，「localhost」和「127.0.0.1」无法使用。",
    "Usenet": "Usenet",
    "User Invoked Search": "用户触发搜索",
    "Username": "用户名",
    "Video": "视频",
    "Waiting": "等待中",
    "Waiting to Import": "等待导入",
    "Waiting to Process": "等待处理",
    "Wanted": "想要",
    "Warning": "警告",
    "Watch": "观看",
    "Watch Trailer": "观看预告片",
    "Website": "网站",
    "Weight": "权重",
    "What happened?": "发生了什么？",
    "Notifications will not route reliably until each instance has been given a unique \"Instance Name\" in the web interface under \"Settings > General\".": "除非每个实例在 Web 界面的「设置 > 通用」中被赋予唯一的「实例名称」，否则通知可能无法可靠路由。",
    "Wrong Instance Type": "错误的实例类型",
    "Year": "年份",
    "Yes": "是",
    "Yesterday": "昨天",

    # === Notification template strings ===
    "NOTIFICATION_APPLICATION_UPDATE": "%@ 已更新",
    "NOTIFICATION_EPISODE_DOWNGRADE": "剧集在 %@ 上已降级",
    "NOTIFICATION_EPISODE_DOWNGRADE_BODY": "从 %1$@ 降级至 %2$@",
    "NOTIFICATION_EPISODE_DOWNLOAD": "剧集在 %@ 上已下载",
    "NOTIFICATION_EPISODE_DOWNLOAD_BODY": "%@（S%@ E%@）",
    "NOTIFICATION_EPISODE_FILE_DELETED": "剧集文件在 %@ 上已删除",
    "NOTIFICATION_EPISODE_FILE_DELETED_BODY": "%@（S%@ E%@）",
    "NOTIFICATION_EPISODE_GRAB": "剧集在 %@ 上下载中",
    "NOTIFICATION_EPISODE_GRAB_SUBTITLE": "%@（S%@ E%@）",
    "NOTIFICATION_EPISODE_UPGRADE": "剧集在 %@ 上已升级",
    "NOTIFICATION_EPISODE_UPGRADE_BODY": "从 %1$@ 升级至 %2$@",
    "NOTIFICATION_EPISODE_UPGRADE_SUBTITLE": "%@（S%@ E%@）",
    "NOTIFICATION_EPISODES_DOWNLOAD": "%2$@ 集已在 %1$@ 上下载",
    "NOTIFICATION_EPISODES_DOWNLOAD_BODY": "%@（第 %@ 季）",
    "NOTIFICATION_EPISODES_GRAB": "%2$@ 集正在 %1$@ 上下载",
    "NOTIFICATION_EPISODES_GRAB_BODY": "正在从 %2$@ 下载 %1$@",
    "NOTIFICATION_EPISODES_GRAB_SUBTITLE": "%@（第 %@ 季）",
    "NOTIFICATION_HEALTH": "%@ 出现健康问题",
    "NOTIFICATION_HEALTH_RESTORED": "%@ 健康问题已解决",
    "NOTIFICATION_MANUAL_INTERACTION_REQUIRED": "%@ 需要手动操作",
    "NOTIFICATION_MOVIE_ADDED": "电影在 %@ 上已添加",
    "NOTIFICATION_MOVIE_ADDED_BODY": "%@（%@）",
    "NOTIFICATION_MOVIE_DELETED": "电影在 %@ 上已删除",
    "NOTIFICATION_MOVIE_DELETED_BODY": "%@（%@）",
    "NOTIFICATION_MOVIE_DOWNGRADE": "电影在 %@ 上已降级",
    "NOTIFICATION_MOVIE_DOWNGRADE_BODY": "从 %1$@ 降级至 %2$@",
    "NOTIFICATION_MOVIE_DOWNLOAD": "电影在 %@ 上已下载",
    "NOTIFICATION_MOVIE_DOWNLOAD_BODY": "%@（%@）",
    "NOTIFICATION_MOVIE_FILE_DELETED": "电影文件在 %@ 上已删除",
    "NOTIFICATION_MOVIE_FILE_DELETED_BODY": "%@（%@）",
    "NOTIFICATION_MOVIE_GRAB": "电影在 %@ 上下载中",
    "NOTIFICATION_MOVIE_GRAB_BODY": "正在从 %2$@ 下载 %1$@",
    "NOTIFICATION_MOVIE_GRAB_SUBTITLE": "%@（%@）",
    "NOTIFICATION_MOVIE_UPGRADE": "电影在 %@ 上已升级",
    "NOTIFICATION_MOVIE_UPGRADE_BODY": "从 %1$@ 升级至 %2$@",
    "NOTIFICATION_MOVIE_UPGRADE_SUBTITLE": "%@（%@）",
    "NOTIFICATION_SERIES_ADDED": "剧集在 %@ 上已添加",
    "NOTIFICATION_SERIES_ADDED_BODY": "%@（%@）",
    "NOTIFICATION_SERIES_DELETED": "剧集在 %@ 上已删除",
    "NOTIFICATION_SERIES_DELETED_BODY": "%@（%@）",
    "NOTIFICATION_TEST": "测试通知",
    "NOTIFICATION_TEST_BODY": "这是一条测试通知。",
}


def needs_review(entry):
    """Check if a zh-Hans localization entry has needs_review state."""
    su = entry.get("stringUnit")
    if su and su.get("state") == "needs_review":
        return True
    var = entry.get("variations", {}).get("plural", {})
    for form_entry in var.values():
        if form_entry.get("stringUnit", {}).get("state") == "needs_review":
            return True
    return False


def translate_plurals(zh_entry, en_entry):
    """Translate all plural forms in a zh-Hans entry."""
    en_var = en_entry.get("variations", {}).get("plural", {})
    zh_var = zh_entry.get("variations", {}).get("plural", {})

    for form_key, zh_form in zh_var.items():
        su = zh_form.get("stringUnit")
        if su and su.get("state") == "needs_review":
            # Get the English value for this form (the zh-Hans currently has it)
            en_value = su.get("value", "")

            # Look up translation
            translated = TRANSLATIONS.get(en_value)
            if translated is not None:
                su["value"] = translated
                su["state"] = "translated"
            else:
                print(f"  WARNING: No translation for plural form '{form_key}' value {en_value!r}", file=sys.stderr)


def translate_string_unit(zh_entry, source_key):
    """Translate the stringUnit in a zh-Hans entry."""
    su = zh_entry.get("stringUnit")
    if su and su.get("state") == "needs_review":
        translated = TRANSLATIONS.get(source_key)
        if translated is not None:
            su["value"] = translated
            su["state"] = "translated"
        else:
            print(f"  WARNING: No translation for key {source_key!r}", file=sys.stderr)


def main():
    filepath = "/root/workspace/orbix/app/Ruddarr/Localizable.xcstrings"

    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)

    strings = data.get("strings", {})
    total_keys = len(strings)
    translated_count = 0
    skipped_count = 0

    for key, entry in strings.items():
        locs = entry.get("localizations", {})
        zh = locs.get("zh-Hans")
        en = locs.get("en")

        if not zh or not en:
            continue

        if not needs_review(zh):
            continue

        # Handle variations (plural forms)
        if "variations" in zh:
            translate_plurals(zh, en)
            translated_count += 1
        elif "stringUnit" in zh:
            translate_string_unit(zh, key)
            translated_count += 1

    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")

    print(f"Processed {total_keys} keys total.", file=sys.stderr)
    print(f"Translated {translated_count} zh-Hans entries.", file=sys.stderr)

    # Verify no needs_review remain
    with open(filepath, "r", encoding="utf-8") as f:
        data2 = json.load(f)
    remaining = 0
    for key, entry in data2.get("strings", {}).items():
        zh = entry.get("localizations", {}).get("zh-Hans", {})
        su = zh.get("stringUnit")
        if su and su.get("state") == "needs_review":
            remaining += 1
        var = zh.get("variations", {}).get("plural", {})
        for fe in var.values():
            if fe.get("stringUnit", {}).get("state") == "needs_review":
                remaining += 1

    if remaining > 0:
        print(f"WARNING: {remaining} zh-Hans entries still have needs_review state.", file=sys.stderr)
    else:
        print("All zh-Hans entries now have 'translated' state.", file=sys.stderr)


if __name__ == "__main__":
    main()
